[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.20.1"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

