sudo: false
language: rust
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
rust:
    - stable
    - beta
    - nightly
cache: cargo
matrix:
    allow_failures:
        - rust: nightly
before_script:
    - export LLVM=clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04
    - wget http://llvm.org/releases/${LLVM_VERSION}/${LLVM}.tar.xz
    - mkdir llvm;
    - tar -xf ${LLVM}.tar.xz -C llvm --strip-components=1;
    - export LIBCLANG_PATH=`pwd`/llvm/lib/
    - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
    - travis-cargo build
    - travis-cargo doc
after_success:
    - git config user.name "Travis-CI Doc Bot"
    - git config user.email "willusher.life@gmail.com"
    - travis-cargo --only stable doc-upload
env:
  matrix:
  - LLVM_VERSION=3.8.0
  global:
    secure: WwruT8gXkwGD3iojTU2iemzttaAk2c2irIlocge27xSaOKUGzZWV7ZEDQR56VG8Y1fQBA9kEYB+G7yltPwWh8LRHNrKvjB6t+w0hXXIildbj1Wt7D+u5hRsgWYcYBTtlJLyCvNAbJVkeVImJwDaAjwAk0u3ZPLBM9NBkdlQfjj8=

