sudo: false
language: rust
cache: cargo
matrix:
    allow_failures:
        - os: windows
    include:
        - os: linux
          dist: xenial
          env:
              - LLVM_VERSION=7.0.1
              - secure: WwruT8gXkwGD3iojTU2iemzttaAk2c2irIlocge27xSaOKUGzZWV7ZEDQR56VG8Y1fQBA9kEYB+G7yltPwWh8LRHNrKvjB6t+w0hXXIildbj1Wt7D+u5hRsgWYcYBTtlJLyCvNAbJVkeVImJwDaAjwAk0u3ZPLBM9NBkdlQfjj8=
          rust: stable
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
        - os: linux
          dist: xenial
          env: LLVM_VERSION=8.0.0
          rust: beta
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
        - os: osx
          osx_image: xcode9.4
          rust: stable
        - os: windows
          rust: stable
before_script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          export TRAVIS_OS_NAME=macOS;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          export LLVM=clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-16.04;
          wget http://llvm.org/releases/${LLVM_VERSION}/${LLVM}.tar.xz;
          mkdir llvm;
          tar -xf ${LLVM}.tar.xz -C llvm --strip-components=1;
          export LIBCLANG_PATH=`pwd`/llvm/lib/;
      fi
    - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then
          wget -O ispc.tar.gz https://downloads.sourceforge.net/project/ispcmirror/v1.11.0/ispc-v1.11.0-${TRAVIS_OS_NAME}.tar.gz;
          tar -xvf ispc.tar.gz;
      else
          wget https://www.dl.dropboxusercontent.com/s/2yrhzzf4xt0ov85/LLVM-8.0.0.zip?dl=1
          7z x LLVM-8.0.0.zip -y;
          export PATH=$PATH:`pwd`/LLVM-8.0.0/;
          wget -O ispc.tar.gz https://downloads.sourceforge.net/project/ispcmirror/v1.11.0/ispc-v1.11.0-${TRAVIS_OS_NAME}.zip;
          7z x ispc.tar.gz -y;
      fi
    - export PATH=$PATH:`pwd`/ispc-v1.11.0-linux/bin/:`pwd`/ispc-v1.11.0-macOS/bin/:`pwd`/ispc-v1.11.0-windows/bin
    - ispc --version
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
          pip install 'travis-cargo<0.2' --user;
          export PATH=$HOME/.local/bin:$PATH;
      fi
    - if [[ "$TRAVIS_OS_NAME" == "macOS" ]]; then export TRAVIS_OS_NAME=osx; fi
script:
    - cargo build
    - cargo test
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cargo doc; fi
    - for d in `ls examples/`; do
          cd examples/${d}/;
          pwd;
          if [[ "$d" == "simple" ]]; then
            cargo build --features ispc;
          fi;
          cargo build;
          if [[ "$?" != "0" ]]; then exit 1; fi;
          cd ../../;
      done
after_success:
    - git config user.name "Travis-CI Doc Bot"
    - git config user.email "willusher.life@gmail.com"
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis-cargo --only stable doc-upload; fi

