[package]
name = "custom_tasksys"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
libc = "0.2.43"
aligned_alloc = "0.1.3"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

