[package]
name = "aobench"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.17.0"
rand = "0.3.18"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

