[package]
name = "rt"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.9.0"
rand = "0.3.14"
serde_json = "0.7.4"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

