[package]
name = "ddvol"
version = "0.1.0"
authors = ["Will Usher <willusher.life@gmail.com>"]
build = "build.rs"

[dependencies]
image = "0.9.0"
rand = "0.3.14"
num = "0.1.34"
serde_json = "0.7.4"
docopt = "0.6.81"
rustc-serialize = "0.3.19"
ispc = { path = "../../" }

[build-dependencies]
ispc = { path = "../../" }

